### ISSUE TITLE
Proofread Roadmap

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#68]
https://unikube.io/docs/roadmap/

**Comment by marty-2015** [comment]
- [x] Named Cluster State (Please check file name - asset loader - again @Schille)
- [ ] Helm Overrides
- [ ] Health check for projects
- [ ] Remote Cluster Provider

**Comment by marty-2015** [comment]
To Dos @Schille
- Named Cluster State: Please check file name/slug - asset loader - again
- Health Check for Projects: Are there two health checks described in the text? One is called "Project Health Check", the other one is called "Project Check service" - If so, a new headline in between would be helpful. If its one and the same check, the naming should be consistent.
